"""add_is_completed_to_habits

Revision ID: 2be223ab42e0
Revises: fd6ea4b988ba
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be223ab42e0'
down_revision: Union[str, None] = 'fd6ea4b988ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('habits', sa.Column('is_completed', sa.Boolean(), nullable=True))
    
    # Обновляем существующие записи
    op.execute("UPDATE habits SET is_completed = false WHERE is_completed IS NULL")
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('habits', 'is_completed',
                    existing_type=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'is_completed')
    # ### end Alembic commands ###
