"""add_mastery_progress_and_target_date

Revision ID: 9a06826eddf0
Revises: 2be223ab42e0
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a06826eddf0'
down_revision: Union[str, None] = '2be223ab42e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонки как nullable
    op.add_column('habits', sa.Column('target_date', sa.Date(), nullable=True))
    op.add_column('habits', sa.Column('mastery_progress', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('mastery_goal', sa.Integer(), nullable=True))
    
    # Обновляем существующие записи
    op.execute("UPDATE habits SET mastery_progress = 0 WHERE mastery_progress IS NULL")
    op.execute("UPDATE habits SET mastery_goal = 100 WHERE mastery_goal IS NULL")
    
    # Теперь делаем колонки NOT NULL
    op.alter_column('habits', 'mastery_progress',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.alter_column('habits', 'mastery_goal',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'mastery_goal')
    op.drop_column('habits', 'mastery_progress')
    op.drop_column('habits', 'target_date')
    # ### end Alembic commands ###
