"""add password_hash to users

Revision ID: b424326f0834
Revises: 5f89e482fde1
Create Date: 2024-04-22 14:17:34.127000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b424326f0834'
down_revision: Union[str, None] = '5f89e482fde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_completed_date')
    op.drop_column('users', 'max_streak')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
